### PR TITLE
Fix event page bugs

### PR DESCRIPTION
**Pull request by ofekashery**
- Fix rendering for events without website link
- Fix rendering and improve UI for events without playoff matches

### CODE REVIEW

**Comment by fangeugene** [comment]
How does this handle events without qual matches? e.g. Einstein

**Comment by ofekashery** [comment]
Good catch! Fixed it.

## Full Data
image

## Just Quals
image

## Just Playoff
image

## No Data
image

**Comment by ofekashery** [comment]
By the way, it looks like the playoff bracket is broken if there are no quarterfinal matches.

**Comment by fangeugene** [comment]
> By the way, it looks like the playoff bracket is broken if there are no quarterfinal matches.

Hmmm good to know.

Other than that, looks good. We can probably design a better no data view in the future, but this is good enough for now.

**Pull request merged**
